# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='counter.proto',
  package='project.outer.servers',
  syntax='proto3',
  serialized_options=b'\n\025project.outer.serversB\017RouteGuideProtoP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcounter.proto\x12\x15project.outer.servers\"\"\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04word\x18\x02 \x01(\t\"%\n\x13NumberOfOccurrences\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32]\n\x07\x43ounter\x12R\n\x05\x43ount\x12\x1b.project.outer.servers.Text\x1a*.project.outer.servers.NumberOfOccurrences\"\x00\x42\x30\n\x15project.outer.serversB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3'
)




_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='project.outer.servers.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='project.outer.servers.Text.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word', full_name='project.outer.servers.Text.word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=74,
)


_NUMBEROFOCCURRENCES = _descriptor.Descriptor(
  name='NumberOfOccurrences',
  full_name='project.outer.servers.NumberOfOccurrences',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='project.outer.servers.NumberOfOccurrences.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['NumberOfOccurrences'] = _NUMBEROFOCCURRENCES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:project.outer.servers.Text)
  })
_sym_db.RegisterMessage(Text)

NumberOfOccurrences = _reflection.GeneratedProtocolMessageType('NumberOfOccurrences', (_message.Message,), {
  'DESCRIPTOR' : _NUMBEROFOCCURRENCES,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:project.outer.servers.NumberOfOccurrences)
  })
_sym_db.RegisterMessage(NumberOfOccurrences)


DESCRIPTOR._options = None

_COUNTER = _descriptor.ServiceDescriptor(
  name='Counter',
  full_name='project.outer.servers.Counter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='Count',
    full_name='project.outer.servers.Counter.Count',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_NUMBEROFOCCURRENCES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTER)

DESCRIPTOR.services_by_name['Counter'] = _COUNTER

# @@protoc_insertion_point(module_scope)
